FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o stress-test cmd/cli/main.go

FROM alpine
COPY --from=builder /app/stress-test .
ENTRYPOINT ["/stress-test"]
CMD ["--help"]