FROM golang:1.24-alpine AS builder

WORKDIR /app

# Instalar certificados CA no builder
RUN apk add --no-cache ca-certificates

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app cmd/app/main.go

FROM scratch AS prod
WORKDIR /app

# Copiar certificados do builder
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /app/app .
COPY --from=builder /app/.env .

ENTRYPOINT ["./app"]
