services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  k6:
    image: grafana/k6:latest
    container_name: k6

    ports:
      - '6565:6565'
    volumes:
      - ./scripts/k6:/scripts
    environment:
      - K6_WEB_DASHBOARD=true
    env_file:
      - .env
    profiles:
      - test

volumes:
  redis-data:
    driver: local
