FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o rate-limiter cmd/main.go

FROM scratch as runner
WORKDIR /app
COPY --from=builder /app/rate-limiter .
ENTRYPOINT ["./rate-limiter"]
