FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . /app

RUN go build -o service-a /app/cmd/main.go

FROM scratch AS runner

WORKDIR /app

COPY --from=builder /app/service-a /app/service-a

ENTRYPOINT ["/app/service-a"]
