receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  debug:
    verbosity: detailed

  # otlp:
  #   endpoint: jaeger-all-in-one:4317
  #   tls:
  #     insecure: true

  zipkin:
    endpoint: 'http://zipkin:9411/api/v2/spans'
    format: proto
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
