openapi: 3.0.0
info:
  title: API de Temperatura por CEP
  description: |
    API para consulta de temperatura atual a partir de um CEP.
    A API utiliza o serviço ViaCEP para obter a cidade correspondente ao CEP
    e o WeatherAPI para obter a temperatura atual da cidade.
  version: 1.0.0
  contact:
    name: André Farias
    url: https://github.com/andrevfarias/goexpert/lab1-cloudrun

servers:
  - url: http://localhost:8080
    description: Servidor de desenvolvimento local

paths:
  /temperature:
    get:
      summary: Consulta temperatura por CEP
      description: |
        Retorna a temperatura atual para a cidade correspondente ao CEP informado.
        A temperatura é retornada em Celsius, Fahrenheit e Kelvin.
      parameters:
        - name: zipcode
          in: query
          description: CEP no formato de 8 dígitos (apenas números)
          required: true
          schema:
            type: string
            pattern: ^\d{8}$
            example: '01001000'
      responses:
        '200':
          description: Temperatura encontrada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
        '400':
          description: CEP não informado
          content:
            text/plain:
              schema:
                type: string
                example: zipcode query parameter is required
        '422':
          description: CEP em formato inválido
          content:
            text/plain:
              schema:
                type: string
                example: invalid zipcode
        '404':
          description: CEP não encontrado
          content:
            text/plain:
              schema:
                type: string
                example: can not find zipcode
        '500':
          description: Erro interno do servidor
          content:
            text/plain:
              schema:
                type: string
                example: internal server error

  /health:
    get:
      summary: Verifica a saúde da API
      description: Endpoint para verificar se a API está funcionando corretamente
      responses:
        '200':
          description: API está funcionando normalmente
          content:
            text/plain:
              schema:
                type: string
                example: OK

components:
  schemas:
    Temperature:
      type: object
      description: Temperatura em diferentes unidades
      properties:
        temp_c:
          type: number
          format: float
          description: Temperatura em graus Celsius
          example: 25.5
        temp_f:
          type: number
          format: float
          description: Temperatura em graus Fahrenheit
          example: 77.9
        temp_k:
          type: number
          format: float
          description: Temperatura em Kelvin
          example: 298.65
      required:
        - temp_c
        - temp_f
        - temp_k
