services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    command: sh -c "/auction"
    networks:
      - localNetwork

  dev:
    image: golang:1.20
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - cmd/auction/.env
    networks:
      - localNetwork
    depends_on:
      - mongodb
    profiles:
      - development

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    name: auction-network
    driver: bridge