# Air configuration file

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/main.go"
bin = "./tmp/app"
full_bin = "./tmp/app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000 # ms
kill_delay = "0s"
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 